## Web scraping de IMDB

Descarga la información correspondiente y guarda en un csv el top de las 250 películas mediante webscraping. Encapsúlalo en un script.

Obtén:
* Título
* Año
* Duración
* Posición
* Rating

In [ ]:


url = "https://www.imdb.com/chart/top/"

<title>IMDb Top 250 movies</title>

In [ ]:
#soup
# top 25

<h3 class="ipc-title__text">The Shawshank Redemption</h3>
1
<h3 class="ipc-title__text">The Godfather</h3>
2
<h3 class="ipc-title__text">The Dark Knight</h3>
3
<h3 class="ipc-title__text">The Godfather Part II</h3>
4
<h3 class="ipc-title__text">12 Angry Men</h3>
5
<h3 class="ipc-title__text">The Lord of the Rings: The Return of the King</h3>
6
<h3 class="ipc-title__text">Schindler's List</h3>
7
<h3 class="ipc-title__text">The Lord of the Rings: The Fellowship of the Ring</h3>
8
<h3 class="ipc-title__text">Pulp Fiction</h3>
9
<h3 class="ipc-title__text">The Good, the Bad and the Ugly</h3>
10
<h3 class="ipc-title__text">The Lord of the Rings: The Two Towers</h3>
11
<h3 class="ipc-title__text">Forrest Gump</h3>
12
<h3 class="ipc-title__text">Fight Club</h3>
13
<h3 class="ipc-title__text">Inception</h3>
14
<h3 class="ipc-title__text">Star Wars: Episode V - The Empire Strikes Back</h3>
15
<h3 class="ipc-title__text">The Matrix</h3>
16
<h3 class="ipc-title__text">GoodFellas</h3>
17
<h3 class="ipc-title__text">Interstellar</h3>
18
<h3 class="ipc-title__text">One Flew Over the Cuckoo's Nest</h3>
19
<h3 class="ipc-title__text">Seven</h3>
20
<h3 class="ipc-title__text">It's a Wonderful Life</h3>
21
<h3 class="ipc-title__text">The Silence of the Lambs</h3>
22
<h3 class="ipc-title__text">Seven Samurai</h3>
23
<h3 class="ipc-title__text">Saving Private Ryan</h3>
24
<h3 class="ipc-title__text">The Green Mile</h3>
25
<h3 class="ipc-title__text">Recently viewed</h3>
26

Título: The Shawshank Redemption
Título: The Godfather
Título: The Dark Knight
Título: The Godfather Part II
Título: 12 Angry Men
Título: The Lord of the Rings: The Return of the King
Título: Schindler's List
Título: The Lord of the Rings: The Fellowship of the Ring
Título: Pulp Fiction
Título: The Good, the Bad and the Ugly
Título: The Lord of the Rings: The Two Towers
Título: Forrest Gump
Título: Fight Club
Título: Inception
Título: Star Wars: Episode V - The Empire Strikes Back
Título: The Matrix
Título: GoodFellas
Título: Interstellar
Título: One Flew Over the Cuckoo's Nest
Título: Seven
Título: It's a Wonderful Life
Título: The Silence of the Lambs
Título: Seven Samurai
Título: Saving Private Ryan
Título: The Green Mile
Título: Recently viewed

Ranking: 1
Ranking: 2
Ranking: 3
Ranking: 4
Ranking: 5
Ranking: 6
Ranking: 7
Ranking: 8
Ranking: 9
Ranking: 10
Ranking: 11
Ranking: 12
Ranking: 13
Ranking: 14
Ranking: 15
Ranking: 16
Ranking: 17
Ranking: 18
Ranking: 19
Ranking: 20
Ranking: 21
Ranking: 22
Ranking: 23
Ranking: 24
Ranking: 25

Rating: 9.3
Rating: 9.2
Rating: 9.1
Rating: 9.0
Rating: 9.0
Rating: 9.0
Rating: 9.0
Rating: 8.9
Rating: 8.8
Rating: 8.8
Rating: 8.8
Rating: 8.8
Rating: 8.8
Rating: 8.8
Rating: 8.7
Rating: 8.7
Rating: 8.7
Rating: 8.7
Rating: 8.6
Rating: 8.6
Rating: 8.6
Rating: 8.6
Rating: 8.6
Rating: 8.6
Rating: 8.6

Año: 1994
Duración: 2h 22m
Año: 1972
Duración: 2h 55m
Año: 2008
Duración: 2h 32m
Año: 1974
Duración: 3h 22m
Año: 1957
Duración: 1h 36m
Año: 2003
Duración: 3h 21m
Año: 1993
Duración: 3h 15m
Año: 2001
Duración: 2h 58m
Año: 1994
Duración: 2h 34m
Año: 1966
Duración: 2h 58m
Año: 2002
Duración: 2h 59m
Año: 1994
Duración: 2h 22m
Año: 1999
Duración: 2h 19m
Año: 2010
Duración: 2h 28m
Año: 1980
Duración: 2h 4m
Año: 1999
Duración: 2h 16m
Año: 1990
Duración: 2h 25m
Año: 2014
Duración: 2h 49m
Año: 1975
Duración: 2h 13m
Año: 1995
Duración: 2h 7m
Año: 1946
Duración: 2h 10m
Año: 1991
Duración: 1h 58m
Año: 1954
Duración: 3h 27m
Año: 1998
Duración: 2h 49m
Año: 1999
Duración: 3h 9m

In [ ]:
# código

df = pd.DataFrame(dict_peliculas)
df.to_csv("top25.csv")
df

,Ranking,Título,Año,Duración,Rating
0,1,The Shawshank Redemption,1994,2h 22m,9.3
1,2,The Godfather,1972,2h 55m,9.2
2,3,The Dark Knight,2008,2h 32m,9.1
3,4,The Godfather Part II,1974,3h 22m,9.0
4,5,12 Angry Men,1957,1h 36m,9.0
5,6,The Lord of the Rings: The Return of the King,2003,3h 21m,9.0
6,7,Schindler's List,1993,3h 15m,9.0
7,8,The Lord of the Rings: The Fellowship of the Ring,2001,2h 58m,8.9
8,9,Pulp Fiction,1994,2h 34m,8.8
9,10,"The Good, the Bad and the Ugly",1966,2h 58m,8.8
10,11,The Lord of the Rings: The Two Towers,2002,2h 59m,8.8
11,12,Forrest Gump,1994,2h 22m,8.8
12,13,Fight Club,1999,2h 19m,8.8
13,14,Inception,2010,2h 28m,8.8
14,15,Star Wars: Episode V - The Empire Strikes Back,1980,2h 4m,8.7
15,16,The Matrix,1999,2h 16m,8.7
16,17,GoodFellas,1990,2h 25m,8.7
17,18,Interstellar,2014,2h 49m,8.7
18,19,One Flew Over the Cuckoo's Nest,1975,2h 13m,8.6
19,20,Seven,1995,2h 7m,8.6
20,21,It's a Wonderful Life,1946,2h 10m,8.6
21,22,The Silence of the Lambs,1991,1h 58m,8.6
22,23,Seven Samurai,1954,3h 27m,8.6
23,24,Saving Private Ryan,1998,2h 49m,8.6
24,25,The Green Mile,1999,3h 9m,8.6

In [37]:
from datetime import datetime

now = datetime.now()

print(str(now).replace(" ","_")[:16])

2026-03-18_22:22

In [38]:
import json

In [ ]:
# todas las películas

[<script type="application/ld+json">{"@type":"ItemList","itemListElement":[{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0111161/","name":"The Shawshank Redemption","description":"A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.","image":"https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9.3,"ratingCount":3168819},"contentRating":"R","genre":"Drama","duration":"PT2H22M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0068646/","name":"The Godfather","description":"The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.","image":"https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9.2,"ratingCount":2213550},"contentRating":"R","genre":"Crime, Drama","duration":"PT2H55M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0468569/","name":"The Dark Knight","description":"When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.","image":"https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9.1,"ratingCount":3146566},"contentRating":"PG-13","genre":"Action, Crime, Drama","duration":"PT2H32M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0071562/","name":"The Godfather Part II","description":"The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.","image":"https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":1487323},"contentRating":"R","genre":"Crime, Drama","duration":"PT3H22M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0050083/","name":"12 Angry Men","description":"The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.","image":"https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":977652},"contentRating":"Approved","genre":"Crime, Drama","duration":"PT1H36M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0167260/","name":"The Lord of the Rings: The Return of the King","description":"Gandalf and Aragorn lead the World of Men against Sauron&apos;s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.","image":"https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":2152640},"contentRating":"PG-13","genre":"Adventure, Drama, Fantasy","duration":"PT3H21M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0108052/","name":"Schindler&apos;s List","description":"In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.","image":"https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":1577900},"contentRating":"R","genre":"Biography, Drama, History","duration":"PT3H15M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0120737/","name":"The Lord of the Rings: The Fellowship of the Ring","description":"A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.","image":"https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.9,"ratingCount":2194051},"contentRating":"PG-13","genre":"Adventure, Drama, Fantasy","duration":"PT2H58M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0110912/","name":"Pulp Fiction","description":"The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.","image":"https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2421630},"contentRating":"R","genre":"Crime, Drama","duration":"PT2H34M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0060196/","name":"Il buono, il brutto, il cattivo","alternateName":"The Good, the Bad and the Ugly","description":"A bounty-hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.","image":"https://m.media-amazon.com/images/M/MV5BMWM5ZjQxM2YtNDlmYi00ZDNhLWI4MWUtN2VkYjBlMTY1ZTkwXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":887377},"contentRating":"R","genre":"Adventure, Drama, Western","duration":"PT2H58M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0167261/","name":"The Lord of the Rings: The Two Towers","description":"While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron&apos;s new ally, Saruman, and his hordes of Isengard.","image":"https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":1945520},"contentRating":"PG-13","genre":"Adventure, Drama, Fantasy","duration":"PT2H59M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0109830/","name":"Forrest Gump","description":"The history of the United States from the 1950s to the &apos;70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.","image":"https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2480675},"contentRating":"PG-13","genre":"Drama, Romance","duration":"PT2H22M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0137523/","name":"Fight Club","description":"An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.","image":"https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2586157},"contentRating":"R","genre":"Crime, Drama, Thriller","duration":"PT2H19M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt1375666/","name":"Inception","description":"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO, but his tragic past may doom the project and his team to disaster.","image":"https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2797149},"contentRating":"PG-13","genre":"Action, Adventure, Sci-Fi","duration":"PT2H28M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0080684/","name":"Star Wars: Episode V - The Empire Strikes Back","description":"After the Empire overpowers the Rebel Alliance, Luke Skywalker begins training with Jedi Master Yoda, while Darth Vader and bounty hunter Boba Fett pursue his friends across the galaxy.","image":"https://m.media-amazon.com/images/M/MV5BMTkxNGFlNDktZmJkNC00MDdhLTg0MTEtZjZiYWI3MGE5NWIwXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":1496951},"contentRating":"PG","genre":"Action, Adventure, Fantasy","duration":"PT2H4M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0133093/","name":"The Matrix","description":"When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.","image":"https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":2234262},"contentRating":"R","genre":"Action, Sci-Fi","duration":"PT2H16M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0099685/","name":"GoodFellas","description":"The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.","image":"https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":1382422},"contentRating":"R","genre":"Biography, Crime, Drama","duration":"PT2H25M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0816692/","name":"Interstellar","description":"When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.","image":"https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":2497325},"contentRating":"PG-13","genre":"Adventure, Drama, Sci-Fi","duration":"PT2H49M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0073486/","name":"One Flew Over the Cuckoo&apos;s Nest","description":"A rebellious convict is sent to a psychiatric hospital for evaluation in 1963 Oregon, and encourages his docile companions to take more control of their lives and defy the tyrannical head nurse.","image":"https://m.media-amazon.com/images/M/MV5BYjBkMjgzMzYtNzRiMS00NDc3LWE4YTUtZjYxYjZhNjNhYzhhXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1152671},"contentRating":"R","genre":"Drama","duration":"PT2H13M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0114369/","name":"Se7en","alternateName":"Seven","description":"Two detectives try to track down a serial killer who chooses his victims based on the Seven Deadly Sins.","image":"https://m.media-amazon.com/images/M/MV5BY2IzNzMxZjctZjUxZi00YzAxLTk3ZjMtODFjODdhMDU5NDM1XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":2006787},"contentRating":"R","genre":"Crime, Drama, Mystery","duration":"PT2H7M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0038650/","name":"It&apos;s a Wonderful Life","description":"An angel is sent from Heaven to help a desperately frustrated businessman see the value of his own life.","image":"https://m.media-amazon.com/images/M/MV5BMDM4OWFhYjEtNTE5Yy00NjcyLTg5N2UtZDQwNDZlYjlmNDU5XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":552745},"contentRating":"PG","genre":"Drama, Family, Fantasy","duration":"PT2H10M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0102926/","name":"The Silence of the Lambs","description":"A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.","image":"https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1711752},"contentRating":"R","genre":"Crime, Drama, Horror","duration":"PT1H58M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0047478/","name":"Shichinin no samurai","alternateName":"Seven Samurai","description":"Farmers from a village exploited by bandits hire a veteran samurai for protection, and he gathers six other samurai to join him.","image":"https://m.media-amazon.com/images/M/MV5BZjliMWExOTMtZDQ3ZS00NWU3LWIyN2EtMjllNzk3ZTNlYzg4XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":400229},"contentRating":"Not Rated","genre":"Action, Drama","duration":"PT3H27M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0120815/","name":"Saving Private Ryan","description":"Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose comrades have been killed in action.","image":"https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1628933},"contentRating":"R","genre":"Drama, War","duration":"PT2H49M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0120689/","name":"The Green Mile","description":"A death row guard learns that a gentle giant in his charge possesses a mysterious gift.","image":"https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1551944},"contentRating":"R","genre":"Crime, Drama, Fantasy","duration":"PT3H9M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0317248/","name":"Cidade de Deus","alternateName":"City of God","description":"In the slums of Rio, two kids&apos; paths diverge as one struggles to become a photographer and the other a kingpin.","image":"https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":866804},"contentRating":"R","genre":"Crime, Drama","duration":"PT2H10M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0118799/","name":"La vita è bella","alternateName":"Life Is Beautiful","description":"When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.","image":"https://m.media-amazon.com/images/M/MV5BZTBhOGYzZjQtYzE0Mi00MGIwLWE0MWYtNzMxNTM2OTFkM2NjXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":808476},"contentRating":"PG-13","genre":"Comedy, Drama, Romance","duration":"PT1H56M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0103064/","name":"Terminator 2: Judgment Day","description":"A cyborg from the future, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from an even more advanced and powerful cyborg.","image":"https://m.media-amazon.com/images/M/MV5BNGMyMGNkMDUtMjc2Ni00NWFlLTgyODEtZTY2MzBiZTg0OWZiXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1277771},"contentRating":"R","genre":"Action, Adventure, Sci-Fi","duration":"PT2H17M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0076759/","name":"Star Wars","alternateName":"Star Wars: Episode IV - A New Hope","description":"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire&apos;s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth ...","image":"https://m.media-amazon.com/images/M/MV5BOGUwMDk0Y2MtNjBlNi00NmRiLTk2MWYtMGMyMDlhYmI4ZDBjXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1562140},"contentRating":"PG","genre":"Action, Adventure, Fantasy","duration":"PT2H1M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0088763/","name":"Back to the Future","description":"Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.","image":"https://m.media-amazon.com/images/M/MV5BZmM3ZjE0NzctNjBiOC00MDZmLTgzMTUtNGVlOWFlOTNiZDJiXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.5,"ratingCount":1443187},"contentRating":"PG","genre":"Adventure, Comedy, Sci-Fi","duration":"PT1H56M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0245429/","name":"Sen to Chihiro no kamikakushi","alternateName":"Spirited Away","description":"During her family&apos;s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.","image":"https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":959703},"contentRating":"PG","genre":"Animation, Adventure, Family","duration":"PT2H4M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0253474/","name":"The Pianist","description":"During WWII, acclaimed Polish musician Wladyslaw faces various struggles as he loses contact with his family. As the situation worsens, he hides in the ruins of Warsaw in order to survive.","image":"https://m.media-amazon.com/images/M/MV5BMjEwNmEwYjgtNTk3ZC00NjljLTg5ZDctZTY3ZGQwZjRkZmQxXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.5,"ratingCount":1006612},"contentRating":"R","genre":"Biography, Drama, Music","duration":"PT2H30M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0172495/","name":"Gladiator","description":"A former Roman General sets

In [ ]:

data

{'@type': 'ItemList',
 'itemListElement': [{'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0111161/',
    'name': 'The Shawshank Redemption',
    'description': 'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9.3,
     'ratingCount': 3168819},
    'contentRating': 'R',
    'genre': 'Drama',
    'duration': 'PT2H22M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0068646/',
    'name': 'The Godfather',
    'description': 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9.2,
     'ratingCount': 2213550},
    'contentRating': 'R',
    'genre': 'Crime, Drama',
    'duration': 'PT2H55M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0468569/',
    'name': 'The Dark Knight',
    'description': 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9.1,
     'ratingCount': 3146566},
    'contentRating': 'PG-13',
    'genre': 'Action, Crime, Drama',
    'duration': 'PT2H32M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0071562/',
    'name': 'The Godfather Part II',
    'description': 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 1487323},
    'contentRating': 'R',
    'genre': 'Crime, Drama',
    'duration': 'PT3H22M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0050083/',
    'name': '12 Angry Men',
    'description': 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 977652},
    'contentRating': 'Approved',
    'genre': 'Crime, Drama',
    'duration': 'PT1H36M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0167260/',
    'name': 'The Lord of the Rings: The Return of the King',
    'description': 'Gandalf and Aragorn lead the World of Men against Sauron&apos;s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 2152640},
    'contentRating': 'PG-13',
    'genre': 'Adventure, Drama, Fantasy',
    'duration': 'PT3H21M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0108052/',
    'name': 'Schindler&apos;s List',
    'description': 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 1577900},
    'contentRating': 'R',
    'genre': 'Biography, Drama, History',
    'duration': 'PT3H15M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0120737/',
    'name': 'The Lord of the Rings: The Fellowship of the Ring',
    'description': 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.9,
     'ratingCount': 2194051},
    'contentRating': 'PG-13',
    'genre': 'Adventure, Drama, Fantasy',
    'duration': 'PT2H58M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0110912/',
    'name': 'Pulp Fiction',
    'description': 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2421630},
    'contentRating': 'R',
    'genre': 'Crime, Drama',
    'duration': 'PT2H34M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0060196/',
    'name': 'Il buono, il brutto, il cattivo',
    'alternateName': 'The Good, the Bad and the Ugly',
    'description': 'A bounty-hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMWM5ZjQxM2YtNDlmYi00ZDNhLWI4MWUtN2VkYjBlMTY1ZTkwXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 887377},
    'contentRating': 'R',
    'genre': 'Adventure, Drama, Western',
    'duration': 'PT2H58M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0167261/',
    'name': 'The Lord of the Rings: The Two Towers',
    'description': 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron&apos;s new ally, Saruman, and his hordes of Isengard.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 1945520},
    'contentRating': 'PG-13',
    'genre': 'Adventure, Drama, Fantasy',
    'duration': 'PT2H59M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0109830/',
    'name': 'Forrest Gump',
    'description': 'The history of the United States from the 1950s to the &apos;70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2480675},
    'contentRating': 'PG-13',
    'genre': 'Drama, Romance',
    'duration': 'PT2H22M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0137523/',
    'name': 'Fight Club',
    'description': 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    'image': 'https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2586157},
    'contentRating': 'R',
    'genre': 'Crime, Drama, Thriller',
    'duration': 'PT2H19M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt1375666/',
    'name': 'Inception',
    'description': 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO, but his tragic past may doom the project and his team to disaster.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2797149},
    'contentRating': 'PG-13',
    'genre': 'Action, Adventure, Sci-Fi',
    'duration': 'PT2H28M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0080684/',
    'name': 'Star Wars: Episode V - The Empire Strikes Back',
    'description': 'After the Empire overpowers the Rebel Alliance, Luke Skywalker begins training with Jedi Master Yoda, while Darth Vader and bounty hunter Boba Fett pursue his friends across the galaxy.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMTkxNGFlNDktZmJkNC00MDdhLTg0MTEtZjZiYWI3MGE5NWIwXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 1496951},
    'contentRating': 'PG',
    'genre': 'Action, Adventure, Fantasy',
    'duration': 'PT2H4M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0133093/',
    'name': 'The Matrix',
    'description': 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    'image': 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 2234262},
    'contentRating': 'R',
    'genre': 'Action, Sci-Fi',
    'duration': 'PT2H16M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0099685/',
    'name': 'GoodFellas',
    'description': 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.',
    'image': 'https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 1382422},
    'contentRating': 'R',
    'genre': 'Biography, Crime, Drama',
    'duration': 'PT2H25M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0816692/',
    'name': 'Interstellar',
    'description': 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 2497325},
    'contentRating': 'PG-13',
    'genre': 'Adventure, Drama, Sci-Fi',
    'duration': 'PT2H49M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0073486/',
    'name': 'One Flew Over the Cuckoo&apos;s Nest',
    'description': 'A rebellious convict is sent to a psychiatric hospital for evaluation in 1963 Oregon, and encourages his docile companions to take more control of their lives and defy the tyrannical head nurse.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYjBkMjgzMzYtNzRiMS00NDc3LWE4YTUtZjYxYjZhNjNhYzhhXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1152671},
    'contentRating': 'R',
    'genre': 'Drama',
    'duration': 'PT2H13M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0114369/',
    'name': 'Se7en',
    'alternateName': 'Seven',
    'description': 'Two detectives try to track down a serial killer who chooses his victims based on the Seven Deadly Sins.',
    'image': 'https://m.media-amazon.com/images/M/MV5BY2IzNzMxZjctZjUxZi00YzAxLTk3ZjMtODFjODdhMDU5NDM1XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 2006787},
    'contentRating': 'R',
    'genre': 'Crime, Drama, Mystery',
    'duration': 'PT2H7M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0038650/',
    'name': 'It&apos;s a Wonderful Life',
    'description': 'An angel is sent from Heaven to help a desperately frustrated businessman see the value of his own life.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMDM4OWFhYjEtNTE5Yy00NjcyLTg5N2UtZDQwNDZlYjlmNDU5XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 552745},
    'contentRating': 'PG',
    'genre': 'Drama, Family, Fantasy',
    'duration': 'PT2H10M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0102926/',
    'name': 'The Silence of the Lambs',
    'description': 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1711752},
    'contentRating': 'R',
    'genre': 'Crime, Drama, Horror',
    'duration': 'PT1H58M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0047478/',
    'name': 'Shichinin no samurai',
    'alternateName': 'Seven Samurai',
    'description': 'Farmers from a village exploited by bandits hire a veteran samurai for protection, and he gathers six other samurai to join him.',
    'image': 'https://m.media-amazon.com/images/M/MV5BZjliMWExOTMtZDQ3ZS00NWU3LWIyN2EtMjllNzk3ZTNlYzg4XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 400229},
    'contentRating': 'Not Rated',
    'genre': 'Action, Drama',
    'duration': 'PT3H27M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0120815/',
    'name': 'Saving Private Ryan',
    'description': 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose comrades have been killed in action.',
    'image': 'https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1628933},
    'contentRating': 'R',
    'genre': 'Drama, War',
    'duration': 'PT2H49M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0120689/',
    'name': 'The Green Mile',
    'description': 'A death row guard learns that a gentle giant in his charge possesses a mysterious gift.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1551944},
    'contentRating': 'R',
    'genre': 'Crime, Drama, Fantasy',
    'duration': 'PT3H9M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0317248/',
    'name': 'Cidade de Deus',
    'alternateName': 'City of God',
    'description': 'In the slums of Rio, two kids&apos; paths diverge as one struggles to become a photographer and the other a kingpin.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 866804},
    'contentRating': 'R',
    'genre': 'Crime, Drama',
    'duration': 'PT2H10M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0118799/',
    'name': 'La vita è bella',
    'alternateName': 'Life Is Beautiful',
    'description': 'When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.',
    'image': 'https://m.media-amazon.com/images/M/MV5BZTBhOGYzZjQtYzE0Mi00MGIwLWE0MWYtNzMxNTM2OTFkM2NjXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 808476},
    'contentRating': 'PG-13',
    'genre': 'Comedy, Drama, Romance',
    'duration': 'PT1H56M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0103064/',
    'name': 'Terminator 2: Judgment Day',
    'description': 'A cyborg from the future, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from an even more advanced and powerful cyborg.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNGMyMGNkMDUtMjc2Ni00NWFlLTgyODEtZTY2MzBiZTg0OWZiXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1277771},
    'contentRating': 'R',
    'genre': 'Action, Adventure, Sci-Fi',
    'duration': 'PT2H17M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0076759/',
    'name': 'Star Wars',
    'alternateName': 'Star Wars: Episode IV - A New Hope',

'The Shawshank Redemption'

,@type,url,name,description,image,aggregateRating,contentRating,genre,duration
@type,Movie,https://www.imdb.com/title/tt0111161/,The Shawshank Redemption,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,AggregateRating,R,Drama,PT2H22M
bestRating,Movie,https://www.imdb.com/title/tt0111161/,The Shawshank Redemption,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,10,R,Drama,PT2H22M
worstRating,Movie,https://www.imdb.com/title/tt0111161/,The Shawshank Redemption,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,1,R,Drama,PT2H22M
ratingValue,Movie,https://www.imdb.com/title/tt0111161/,The Shawshank Redemption,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,9.3,R,Drama,PT2H22M
ratingCount,Movie,https://www.imdb.com/title/tt0111161/,The Shawshank Redemption,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...,3168819,R,Drama,PT2H22M

'2H22M'

Ranking 1
Título: The Shawshank Redemption
Rating: 9.3
Duración: 2H22M
Ranking 2
Título: The Godfather
Rating: 9.2
Duración: 2H55M
Ranking 3
Título: The Dark Knight
Rating: 9.1
Duración: 2H32M
Ranking 4
Título: The Godfather Part II
Rating: 9
Duración: 3H22M
Ranking 5
Título: 12 Angry Men
Rating: 9
Duración: 1H36M
Ranking 6
Título: The Lord of the Rings: The Return of the King
Rating: 9
Duración: 3H21M
Ranking 7
Título: Schindler&apos;s List
Rating: 9
Duración: 3H15M
Ranking 8
Título: The Lord of the Rings: The Fellowship of the Ring
Rating: 8.9
Duración: 2H58M
Ranking 9
Título: Pulp Fiction
Rating: 8.8
Duración: 2H34M
Ranking 10
Título: Il buono, il brutto, il cattivo
Rating: 8.8
Duración: 2H58M
Ranking 11
Título: The Lord of the Rings: The Two Towers
Rating: 8.8
Duración: 2H59M
Ranking 12
Título: Forrest Gump
Rating: 8.8
Duración: 2H22M
Ranking 13
Título: Fight Club
Rating: 8.8
Duración: 2H19M
Ranking 14
Título: Inception
Rating: 8.8
Duración: 2H28M
Ranking 15
Título: Star Wars: Episode V - The Empire Strikes Back
Rating: 8.7
Duración: 2H4M
Ranking 16
Título: The Matrix
Rating: 8.7
Duración: 2H16M
Ranking 17
Título: GoodFellas
Rating: 8.7
Duración: 2H25M
Ranking 18
Título: Interstellar
Rating: 8.7
Duración: 2H49M
Ranking 19
Título: One Flew Over the Cuckoo&apos;s Nest
Rating: 8.6
Duración: 2H13M
Ranking 20
Título: Se7en
Rating: 8.6
Duración: 2H7M
Ranking 21
Título: It&apos;s a Wonderful Life
Rating: 8.6
Duración: 2H10M
Ranking 22
Título: The Silence of the Lambs
Rating: 8.6
Duración: 1H58M
Ranking 23
Título: Shichinin no samurai
Rating: 8.6
Duración: 3H27M
Ranking 24
Título: Saving Private Ryan
Rating: 8.6
Duración: 2H49M
Ranking 25
Título: The Green Mile
Rating: 8.6
Duración: 3H9M
Ranking 26
Título: Cidade de Deus
Rating: 8.6
Duración: 2H10M
Ranking 27
Título: La vita è bella
Rating: 8.6
Duración: 1H56M
Ranking 28
Título: Terminator 2: Judgment Day
Rating: 8.6
Duración: 2H17M
Ranking 29
Título: Star Wars
Rating: 8.6
Duración: 2H1M
Ranking 30
Título: Back to the Future
Rating: 8.5
Duración: 1H56M
Ranking 31
Título: Sen to Chihiro no kamikakushi
Rating: 8.6
Duración: 2H4M
Ranking 32
Título: The Pianist
Rating: 8.5
Duración: 2H30M
Ranking 33
Título: Gladiator
Rating: 8.5
Duración: 2H35M
Ranking 34
Título: Gisaengchung
Rating: 8.5
Duración: 2H12M
Ranking 35
Título: Hotaru no haka
Rating: 8.5
Duración: 1H28M
Ranking 36
Título: Psycho
Rating: 8.5
Duración: 1H49M
Ranking 37
Título: The Lion King
Rating: 8.5
Duración: 1H28M
Ranking 38
Título: Seppuku
Rating: 8.6
Duración: 2H13M
Ranking 39
Título: The Departed
Rating: 8.5
Duración: 2H31M
Ranking 40
Título: Whiplash
Rating: 8.5
Duración: 1H46M
Ranking 41
Título: The Prestige
Rating: 8.5
Duración: 2H10M
Ranking 42
Título: Kill Bill: The Whole Bloody Affair
Rating: 8.8
Duración: 4H13M
Ranking 43
Título: American History X
Rating: 8.5
Duración: 1H59M
Ranking 44
Título: Léon
Rating: 8.5
Duración: 1H50M
Ranking 45
Título: Spider-Man: Across the Spider-Verse
Rating: 8.5
Duración: 2H20M
Ranking 46
Título: Nuovo Cinema Paradiso
Rating: 8.5
Duración: 2H54M
Ranking 47
Título: Casablanca
Rating: 8.5
Duración: 1H42M
Ranking 48
Título: Intouchables
Rating: 8.5
Duración: 1H52M
Ranking 49
Título: The Usual Suspects
Rating: 8.5
Duración: 1H46M
Ranking 50
Título: Alien
Rating: 8.5
Duración: 1H57M
Ranking 51
Título: Django Unchained
Rating: 8.5
Duración: 2H45M
Ranking 52
Título: Modern Times
Rating: 8.5
Duración: 1H27M
Ranking 53
Título: Rear Window
Rating: 8.5
Duración: 1H52M
Ranking 54
Título: C&apos;era una volta il West
Rating: 8.5
Duración: 2H25M
Ranking 55
Título: City Lights
Rating: 8.5
Duración: 1H27M
Ranking 56
Título: Apocalypse Now
Rating: 8.4
Duración: 2H27M
Ranking 57
Título: WALL·E
Rating: 8.4
Duración: 1H38M
Ranking 58
Título: Memento
Rating: 8.4
Duración: 1H53M
Ranking 59
Título: Dune: Part Two
Rating: 8.4
Duración: 2H46M
Ranking 60
Título: Raiders of the Lost Ark
Rating: 8.4
Duración: 1H55M
Ranking 61
Título: Avengers: Infinity War
Rating: 8.4
Duración: 2H29M
Ranking 62
Título: Das Leben der Anderen
Rating: 8.4
Duración: 2H17M
Ranking 63
Título: Spider-Man: Into the Spider-Verse
Rating: 8.4
Duración: 1H57M
Ranking 64
Título: Sunset Blvd.
Rating: 8.4
Duración: 1H50M
Ranking 65
Título: Witness for the Prosecution
Rating: 8.4
Duración: 1H56M
Ranking 66
Título: Paths of Glory
Rating: 8.4
Duración: 1H28M
Ranking 67
Título: The Shining
Rating: 8.4
Duración: 2H26M
Ranking 68
Título: The Great Dictator
Rating: 8.4
Duración: 2H5M
Ranking 69
Título: Inglourious Basterds
Rating: 8.4
Duración: 2H33M
Ranking 70
Título: 12th Fail
Rating: 8.7
Duración: 2H27M
Ranking 71
Título: Aliens
Rating: 8.4
Duración: 2H17M
Ranking 72
Título: Tengoku to jigoku
Rating: 8.4
Duración: 2H23M
Ranking 73
Título: Good Will Hunting
Rating: 8.4
Duración: 2H6M
Ranking 74
Título: Avengers: Endgame
Rating: 8.4
Duración: 3H1M
Ranking 75
Título: The Dark Knight Rises
Rating: 8.4
Duración: 2H44M
Ranking 76
Título: Coco
Rating: 8.4
Duración: 1H45M
Ranking 77
Título: Amadeus
Rating: 8.4
Duración: 2H40M
Ranking 78
Título: Toy Story
Rating: 8.3
Duración: 1H21M
Ranking 79
Título: Kimi no na wa.
Rating: 8.4
Duración: 1H46M
Ranking 80
Título: Das Boot
Rating: 8.3
Duración: 2H29M
Ranking 81
Título: Oldeuboi
Rating: 8.3
Duración: 2H
Ranking 82
Título: Braveheart
Rating: 8.3
Duración: 2H58M
Ranking 83
Título: Mononoke-hime
Rating: 8.3
Duración: 2H13M
Ranking 84
Título: Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
Rating: 8.3
Duración: 1H35M
Ranking 85
Título: 3 Idiots
Rating: 8.4
Duración: 2H50M
Ranking 86
Título: American Beauty
Rating: 8.3
Duración: 2H2M
Ranking 87
Título: Capharnaüm
Rating: 8.4
Duración: 2H6M
Ranking 88
Título: Singin&apos; in the Rain
Rating: 8.3
Duración: 1H43M
Ranking 89
Título: Joker
Rating: 8.3
Duración: 2H2M
Ranking 90
Título: C&apos;era una volta in America
Rating: 8.3
Duración: 3H49M
Ranking 91
Título: Idi i smotri
Rating: 8.3
Duración: 2H22M
Ranking 92
Título: Star Wars: Episode VI - Return of the Jedi
Rating: 8.3
Duración: 2H11M
Ranking 93
Título: Requiem for a Dream
Rating: 8.3
Duración: 1H42M
Ranking 94
Título: Toy Story 3
Rating: 8.3
Duración: 1H43M
Ranking 95
Título: Ikiru
Rating: 8.3
Duración: 2H23M
Ranking 96
Título: Jagten
Rating: 8.3
Duración: 1H55M
Ranking 97
Título: Incendies
Rating: 8.3
Duración: 2H11M
Ranking 98
Título: Eternal Sunshine of the Spotless Mind
Rating: 8.3
Duración: 1H48M
Ranking 99
Título: The Apartment
Rating: 8.3
Duración: 2H5M
Ranking 100
Título: Lawrence of Arabia
Rating: 8.3
Duración: 3H47M
Ranking 101
Título: Heat
Rating: 8.3
Duración: 2H50M
Ranking 102
Título: 2001: A Space Odyssey
Rating: 8.3
Duración: 2H29M
Ranking 103
Título: Reservoir Dogs
Rating: 8.3
Duración: 1H39M
Ranking 104
Título: Scarface
Rating: 8.3
Duración: 2H50M
Ranking 105
Título: Double Indemnity
Rating: 8.3
Duración: 1H47M
Ranking 106
Título: Up
Rating: 8.3
Duración: 1H36M
Ranking 107
Título: North by Northwest
Rating: 8.3
Duración: 2H16M
Ranking 108
Título: Taare Zameen Par
Rating: 8.3
Duración: 2H42M
Ranking 109
Título: Full Metal Jacket
Rating: 8.2
Duración: 1H56M
Ranking 110
Título: M - Eine Stadt sucht einen Mörder
Rating: 8.3
Duración: 1H39M
Ranking 111
Título: Citizen Kane
Rating: 8.2
Duración: 1H59M
Ranking 112
Título: Le fabuleux destin d&apos;Amélie Poulain
Rating: 8.3
Duración: 2H2M
Ranking 113
Título: Vertigo
Rating: 8.2
Duración: 2H8M
Ranking 114
Título: Jodaeiye Nader az Simin
Rating: 8.3
Duración: 2H3M
Ranking 115
Título: Die Hard
Rating: 8.2
Duración: 2H12M
Ranking 116
Título: To Kill a Mockingbird
Rating: 8.2
Duración: 2H9M
Ranking 117
Título: Indiana Jones and the Last Crusade
Rating: 8.2
Duración: 2H7M
Ranking 118
Título: The Sting
Rating: 8.2
Duración: 2H9M
Ranking 119
Título: A Clockwork Orange
Rating: 8.2
Duración: 2H16M
Ranking 120
Título: Metropolis
Rating: 8.2
Duración: 2H33M
Ranking 121
Título: 1917
Rating: 8.2
Duración: 1H59M
Ranking 122
Título: Snatch
Rating: 8.2
Duración: 1H42M
Ranking 123
Título: L.A. Confidential
Rating: 8.2
Duración: 2H18M
Ranking 124
Título: Der Untergang
Rating: 8.2
Duración: 2H36M
Ranking 125
Título: The Wolf of Wall Street
Rating: 8.2
Duración: 3H
Ranking 126
Título: Dangal
Rating: 8.3
Duración: 2H41M
Ranking 127
Título: The Truman Show
Rating: 8.2
Duración: 1H43M
Ranking 128
Título: Ladri di biciclette
Rating: 8.2
Duración: 1H29M
Ranking 129
Título: Oppenheimer
Rating: 8.2
Duración: 3H
Ranking 130
Título: Green Book
Rating: 8.2
Duración: 2H10M
Ranking 131
Título: Shutter Island
Rating: 8.2
Duración: 2H18M
Ranking 132
Título: Judgment at Nuremberg
Rating: 8.3
Duración: 2H59M
Ranking 133
Título: Batman Begins
Rating: 8.2
Duración: 2H20M
Ranking 134
Título: Hamilton
Rating: 8.3
Duración: 2H40M
Ranking 135
Título: Per qualche dollaro in più
Rating: 8.2
Duración: 2H12M
Ranking 136
Título: Taxi Driver
Rating: 8.2
Duración: 1H54M
Ranking 137
Título: Jurassic Park
Rating: 8.2
Duración: 2H7M
Ranking 138
Título: Some Like It Hot
Rating: 8.2
Duración: 2H1M
Ranking 139
Título: There Will Be Blood
Rating: 8.2
Duración: 2H38M
Ranking 140
Título: The Kid
Rating: 8.2
Duración: 1H8M
Ranking 141
Título: The Father
Rating: 8.2
Duración: 1H37M
Ranking 142
Título: All About Eve
Rating: 8.2
Duración: 2H18M
Ranking 143
Título: The Sixth Sense
Rating: 8.2
Duración: 1H47M
Ranking 144
Título: Ran
Rating: 8.2
Duración: 2H40M
Ranking 145
Título: Casino
Rating: 8.2
Duración: 2H58M
Ranking 146
Título: No Country for Old Men
Rating: 8.2
Duración: 2H2M
Ranking 147
Título: The Thing
Rating: 8.2
Duración: 1H49M
Ranking 148
Título: Top Gun: Maverick
Rating: 8.2
Duración: 2H10M
Ranking 149
Título: Prisoners
Rating: 8.2
Duración: 2H33M
Ranking 150
Título: Kill Bill: Vol. 1
Rating: 8.2
Duración: 1H51M
Ranking 151
Título: El laberinto del fauno
Rating: 8.2
Duración: 1H58M
Ranking 152
Título: Unforgiven
Rating: 8.2
Duración: 2H10M
Ranking 153
Título: A Beautiful Mind
Rating: 8.2
Duración: 2H15M
Ranking 154
Título: The Treasure of the Sierra Madre
Rating: 8.2
Duración: 2H6M
Ranking 155
Título: Hauru no ugoku shiro
Rating: 8.2
Duración: 1H59M
Ranking 156
Título: Finding Nemo
Rating: 8.2
Duración: 1H40M
Ranking 157
Título: Klaus
Rating: 8.2
Duración: 1H36M
Ranking 158
Título: Yôjinbô
Rating: 8.2
Duración: 1H50M
Ranking 159
Título: The Great Escape
Rating: 8.2
Duración: 2H52M
Ranking 160
Título: The Elephant Man
Rating: 8.2
Duración: 2H4M
Ranking 161
Título: Monty Python and the Holy Grail
Rating: 8.2
Duración: 1H31M
Ranking 162
Título: Dial M for Murder
Rating: 8.1
Duración: 1H45M
Ranking 163
Título: La meglio gioventù
Rating: 8.4
Duración: 6H14M
Ranking 164
Título: Gekijô-ban Kimetsu no Yaiba Mugen Jô-hen
Rating: 8.4
Duración: 2H35M
Ranking 165
Título: El secreto de sus ojos
Rating: 8.2
Duración: 2H9M
Ranking 166
Título: Gone with the Wind
Rating: 8.2
Duración: 3H58M
Ranking 167
Título: Chinatown
Rating: 8.1
Duración: 2H10M
Ranking 168
Título: Lock, Stock and Two Smoking Barrels
Rating: 8.1
Duración: 1H47M
Ranking 169
Título: V for Vendetta
Rating: 8.1
Duración: 2H12M
Ranking 170
Título: Catch Me If You Can
Rating: 8.1
Duración: 2H21M
Ranking 171
Título: Inside Out
Rating: 8.1
Duración: 1H35M
Ranking 172
Título: Rashômon
Rating: 8.1
Duración: 1H28M
Ranking 173
Título: Three Billboards Outside Ebbing, Missouri
Rating: 8.1
Duración: 1H55M
Ranking 174
Título: Trainspotting
Rating: 8.1
Duración: 1H33M
Ranking 175
Título: The Bridge on the River Kwai
Rating: 8.1
Duración: 2H41M
Ranking 176
Título: Harry Potter and the Deathly Hallows: Part 2
Rating: 8.1
Duración: 2H10M
Ranking 177
Título: Dead Poets Society
Rating: 8.1
Duración: 2H8M
Ranking 178
Título: The Wild Robot
Rating: 8.2
Duración: 1H42M
Ranking 179
Título: Hababam Sinifi: Sinifta Kaldi
Rating: 8.5
Duración: 1H35M
Ranking 180
Título: Warrior
Rating: 8.1
Duración: 2H20M
Ranking 181
Título: Barry Lyndon
Rating: 8.1
Duración: 3H5M
Ranking 182
Título: Fargo
Rating: 8.1
Duración: 1H38M
Ranking 183
Título: Ben-Hur
Rating: 8.1
Duración: 3H32M
Ranking 184
Título: Raging Bull
Rating: 8.1
Duración: 2H9M
Ranking 185
Título: Million Dollar Baby
Rating: 8.1
Duración: 2H12M
Ranking 186
Título: Mad Max: Fury Road
Rating: 8.1
Duración: 2H
Ranking 187
Título: Bacheha-ye aseman
Rating: 8.2
Duración: 1H29M
Ranking 188
Título: Hacksaw Ridge
Rating: 8.1
Duración: 2H19M
Ranking 189
Título: Tonari no Totoro
Rating: 8.1
Duración: 1H26M
Ranking 190
Título: Gran Torino
Rating: 8.1
Duración: 1H56M
Ranking 191
Título: Ratatouille
Rating: 8.1
Duración: 1H51M
Ranking 192
Título: 12 Years a Slave
Rating: 8.1
Duración: 2H14M
Ranking 193
Título: The Grand Budapest Hotel
Rating: 8.1
Duración: 1H39M
Ranking 194
Título: Before Sunrise
Rating: 8.1
Duración: 1H41M
Ranking 195
Título: Salinui chueok
Rating: 8.1
Duración: 2H11M
Ranking 196
Título: Blade Runner
Rating: 8.1
Duración: 1H57M
Ranking 197
Título: How to Train Your Dragon
Rating: 8.1
Duración: 1H38M
Ranking 198
Título: Spider-Man: No Way Home
Rating: 8.1
Duración: 2H28M
Ranking 199
Título: Gone Girl
Rating: 8.1
Duración: 2H29M
Ranking 200
Título: Monsters, Inc.
Rating: 8.1
Duración: 1H32M
Ranking 201
Título: Jaws
Rating: 8.1
Duración: 2H4M
Ranking 202
Título: In the Name of the Father
Rating: 8.1
Duración: 2H13M
Ranking 203
Título: Ford v Ferrari
Rating: 8.1
Duración: 2H32M
Ranking 204
Título: Relatos salvajes
Rating: 8.1
Duración: 2H2M
Ranking 205
Título: The Gold Rush
Rating: 8.1
Duración: 1H35M
Ranking 206
Título: Mary and Max.
Rating: 8.1
Duración: 1H32M
Ranking 207
Título: Sherlock Jr.
Rating: 8.1
Duración: 45M
Ranking 208
Título: The Deer Hunter
Rating: 8.1
Duración: 3H3M
Ranking 209
Título: Le salaire de la peur
Rating: 8.1
Duración: 2H36M
Ranking 210
Título: The General
Rating: 8.1
Duración: 1H18M
Ranking 211
Título: Logan
Rating: 8.1
Duración: 2H17M
Ranking 212
Título: Rocky
Rating: 8.1
Duración: 2H
Ranking 213
Título: Mr. Smith Goes to Washington
Rating: 8.1
Duración: 2H9M
Ranking 214
Título: Tôkyô monogatari
Rating: 8.1
Duración: 2H17M
Ranking 215
Título: On the Waterfront
Rating: 8.1
Duración: 1H48M
Ranking 216
Título: Pirates of the Caribbean: The Curse of the Black Pearl
Rating: 8.1
Duración: 2H23M
Ranking 217
Título: Smultronstället
Rating: 8.1
Duración: 1H32M
Ranking 218
Título: Spotlight
Rating: 8.1
Duración: 2H9M
Ranking 219
Título: Koe no katachi
Rating: 8.2
Duración: 2H10M
Ranking 220
Título: La haine
Rating: 8.1
Duración: 1H38M
Ranking 221
Título: The Terminator
Rating: 8.1
Duración: 1H47M
Ranking 222
Título: Jai Bhim
Rating: 8.6
Duración: 2H44M
Ranking 223
Título: The Third Man
Rating: 8.1
Duración: 1H44M
Ranking 224
Título: The Sound of Music
Rating: 8.1
Duración: 2H54M
Ranking 225
Título: Maharaja
Rating: 8.3
Duración: 2H21M
Ranking 226
Título: The Big Lebowski
Rating: 8.1
Duración: 1H57M
Ranking 227
Título: The Best Years of Our Lives
Rating: 8.1
Duración: 2H50M
Ranking 228
Título: Det sjunde inseglet
Rating: 8.1
Duración: 1H36M
Ranking 229
Título: Before Sunset
Rating: 8.1
Duración: 1H20M
Ranking 230
Título: Room
Rating: 8.1
Duración: 1H58M
Ranking 231
Título: Gekijô-ban Chensô Man Reze-hen
Rating: 8.3
Duración: 1H40M
Ranking 232
Título: Hotel Rwanda
Rating: 8.1
Duración: 2H1M
Ranking 233
Título: The Incredibles
Rating: 8
Duración: 1H55M
Ranking 234
Título: Platoon
Rating: 8.1
Duración: 2H
Ranking 235
Título: Hachi: A Dog&apos;s Tale
Rating: 8.1
Duración: 1H33M
Ranking 236
Título: The Exorcist
Rating: 8.1
Duración: 2H2M
Ranking 237
Título: Rush
Rating: 8.1
Duración: 2H3M
Ranking 238
Título: The Iron Giant
Rating: 8.1
Duración: 1H26M
Ranking 239
Título: The Wizard of Oz
Rating: 8.1
Duración: 1H42M
Ranking 240
Título: Stand by Me
Rating: 8.1
Duración: 1H29M
Ranking 241
Título: La passion de Jeanne d&apos;Arc
Rating: 8.1
Duración: 1H54M
Ranking 242
Título: Babam ve Oglum
Rating: 8.2
Duración: 1H52M
Ranking 243
Título: La battaglia di Algeri
Rating: 8.1
Duración: 2H1M
Ranking 244
Título: Ah-ga-ssi
Rating: 8.1
Duración: 2H25M
Ranking 245
Título: Network
Rating: 8.1
Duración: 2H1M
Ranking 246
Título: Drishyam
Rating: 8.2
Duración: 2H43M
Ranking 247
Título: The Grapes of Wrath
Rating: 8.1
Duración: 2H9M
Ranking 248
Título: Gangs of Wasseypur
Rating: 8.2
Duración: 5H21M
Ranking 249
Título: To Be or Not to Be
Rating: 8.1
Duración: 1H39M
Ranking 250
Título: Laapataa Ladies
Rating: 8.3
Duración: 2H2M

1994
1
1972
2
2008
3
1974
4
1957
5
2003
6
1993
7
2001
8
1994
9
1966
10
2002
11
1994
12
1999
13
2010
14
1980
15
1999
16
1990
17
2014
18
1975
19
1995
20
1946
21
1991
22
1954
23
1998
24
1999
25
2002
26
1997
27
1991
28
1977
29
1985
30
2001
31
2002
32
2000
33
2019
34
1988
35
1960
36
1994
37
1962
38
2006
39
2014
40
2006
41
2004
42
1998
43
1994
44
2023
45
1988
46
1942
47
2011
48
1995
49
1979
50
2012
51
1936
52
1954
53
1968
54
1931
55
1979
56
2008
57
2000
58
2024
59
1981
60
2018
61
2006
62
2018
63
1950
64
1957
65
1957
66
1980
67
1940
68
2009
69
2023
70
1986
71
1963
72
1997
73
2019
74
2012
75
2017
76
1984
77
1995
78
2016
79
1981
80
2003
81
1995
82
1997
83
1964
84
2009
85
1999
86
2018
87
1952
88
2019
89
1984
90
1985
91
1983
92
2000
93
2010
94
1952
95
2012
96
2010
97
2004
98
1960
99
1962
100
1995
101
1968
102
1992
103
1983
104
1944
105
2009
106
1959
107
2007
108
1987
109
1931
110
1941
111
2001
112
1958
113
2011
114
1988
115
1962
116
1989
117
1973
118
1971
119
1927
120
2019
121
2000
122
1997
123
2004
124
2013
125
2016
126
1998
127
1948
128
2023
129
2018
130
2010
131
1961
132
2005
133
2020
134
1965
135
1976
136
1993
137
1959
138
2007
139
1921
140
2020
141
1950
142
1999
143
1985
144
1995
145
2007
146
1982
147
2022
148
2013
149
2003
150
2006
151
1992
152
2001
153
1948
154
2004
155
2003
156
2019
157
1961
158
1963
159
1980
160
1975
161
1954
162
2003
163
2025
164
2009
165
1939
166
1974
167
1998
168
2005
169
2002
170
2015
171
1950
172
2017
173
1996
174
1957
175
2011
176
1989
177
2024
178
1975
179
2011
180
1975
181
1996
182
1959
183
1980
184
2004
185
2015
186
1997
187
2016
188
1988
189
2008
190
2007
191
2013
192
2014
193
1995
194
2003
195
1982
196
2010
197
2021
198
2014
199
2001
200
1975
201
1993
202
2019
203
2014
204
1925
205
2009
206
1924
207
1978
208
1953
209
1926
210
2017
211
1976
212
1939
213
1953
214
1954
215
2003
216
1957
217
2015
218
2016
219
1995
220
1984
221
2021
222
1949
223
1965
224
2024
225
1998
226
1946
227
1957
228
2004
229
2015
230
2025
231
2004
232
2004
233
1986
234
2009
235
1973
236
2013
237
1999
238
1939
239
1986
240
1928
241
2005
242
1966
243
2016
244
1976
245
2015
246
1940
247
2012
248
1942
249
2023
250

In [ ]:

pd.DataFrame(dict_peliculas)

     Ranking                    Título   Año Duración  Rating
0          1  The Shawshank Redemption  1994    2H22M     9.3
1          2             The Godfather  1972    2H55M     9.2
2          3           The Dark Knight  2008    2H32M     9.1
3          4     The Godfather Part II  1974    3H22M     9.0
4          5              12 Angry Men  1957    1H36M     9.0
..       ...                       ...   ...      ...     ...
245      246                  Drishyam  2015    2H43M     8.2
246      247       The Grapes of Wrath  1940     2H9M     8.1
247      248        Gangs of Wasseypur  2012    5H21M     8.2
248      249        To Be or Not to Be  1942    1H39M     8.1
249      250           Laapataa Ladies  2023     2H2M     8.3

[250 rows x 5 columns]