## Ejercicio 1
Calcula la proporción de visitantes los dominogos del siguiente dataset.
Pasos recomendados:
- Entender el tipo de los datos
- Transformar el tipo de las fechas de los datos
- Crear una columna nueva llamada weekday

In [28]:
import pandas as pd

# Run this cell to create the dataset
from datetime import datetime

dates = [f"2026-01-{day:02d}" for day in range(1, 32)]
visitors = [270, 470, 300, 420, 390, 360, 330, 300, 420, 490, 480, 410, 460, 480, 220, 450, 390, 430, 400, 350, 380, 290, 330, 490, 420, 470, 340, 500, 260, 420, 400]

df_visitations = pd.DataFrame({'date': dates, 'visitors': visitors})
df_visitations.head()

         date  visitors
0  2026-01-01       270
1  2026-01-02       470
2  2026-01-03       300
3  2026-01-04       420
4  2026-01-05       390

In [29]:
df_visitations['date'] = pd.to_datetime(df_visitations['date'])

In [30]:
df_visitations['weekday'] = df_visitations['date'].dt.day
df_visitations['weekday_name'] = df_visitations['date'].dt.day_name()

In [31]:
df_visitations

         date  visitors  weekday weekday_name
0  2026-01-01       270        1     Thursday
1  2026-01-02       470        2       Friday
2  2026-01-03       300        3     Saturday
3  2026-01-04       420        4       Sunday
4  2026-01-05       390        5       Monday
5  2026-01-06       360        6      Tuesday
6  2026-01-07       330        7    Wednesday
7  2026-01-08       300        8     Thursday
8  2026-01-09       420        9       Friday
9  2026-01-10       490       10     Saturday
10 2026-01-11       480       11       Sunday
11 2026-01-12       410       12       Monday
12 2026-01-13       460       13      Tuesday
13 2026-01-14       480       14    Wednesday
14 2026-01-15       220       15     Thursday
15 2026-01-16       450       16       Friday
16 2026-01-17       390       17     Saturday
17 2026-01-18       430       18       Sunday
18 2026-01-19       400       19       Monday
19 2026-01-20       350       20      Tuesday
20 2026-01-21       380       21    Wednesday
21 2026-01-22       290       22     Thursday
22 2026-01-23       330       23       Friday
23 2026-01-24       490       24     Saturday
24 2026-01-25       420       25       Sunday
25 2026-01-26       470       26       Monday
26 2026-01-27       340       27      Tuesday
27 2026-01-28       500       28    Wednesday
28 2026-01-29       260       29     Thursday
29 2026-01-30       420       30       Friday
30 2026-01-31       400       31     Saturday

In [32]:
df_visitations['date'].dt.strftime("%A")

0      Thursday
1        Friday
2      Saturday
3        Sunday
4        Monday
5       Tuesday
6     Wednesday
7      Thursday
8        Friday
9      Saturday
10       Sunday
11       Monday
12      Tuesday
13    Wednesday
14     Thursday
15       Friday
16     Saturday
17       Sunday
18       Monday
19      Tuesday
20    Wednesday
21     Thursday
22       Friday
23     Saturday
24       Sunday
25       Monday
26      Tuesday
27    Wednesday
28     Thursday
29       Friday
30     Saturday
Name: date, dtype: object

In [33]:
df_visitations['date'].dt.strftime("The date is %A, %d, the year is %Y")

0      The date is Thursday, 01, the year is 2026
1        The date is Friday, 02, the year is 2026
2      The date is Saturday, 03, the year is 2026
3        The date is Sunday, 04, the year is 2026
4        The date is Monday, 05, the year is 2026
5       The date is Tuesday, 06, the year is 2026
6     The date is Wednesday, 07, the year is 2026
7      The date is Thursday, 08, the year is 2026
8        The date is Friday, 09, the year is 2026
9      The date is Saturday, 10, the year is 2026
10       The date is Sunday, 11, the year is 2026
11       The date is Monday, 12, the year is 2026
12      The date is Tuesday, 13, the year is 2026
13    The date is Wednesday, 14, the year is 2026
14     The date is Thursday, 15, the year is 2026
15       The date is Friday, 16, the year is 2026
16     The date is Saturday, 17, the year is 2026
17       The date is Sunday, 18, the year is 2026
18       The date is Monday, 19, the year is 2026
19      The date is Tuesday, 20, the year is 2026
20    The date is Wednesday, 21, the year is 2026
21     The date is Thursday, 22, the year is 2026
22       The date is Friday, 23, the year is 2026
23     The date is Saturday, 24, the year is 2026
24       The date is Sunday, 25, the year is 2026
25       The date is Monday, 26, the year is 2026
26      The date is Tuesday, 27, the year is 2026
27    The date is Wednesday, 28, the year is 2026
28     The date is Thursday, 29, the year is 2026
29       The date is Friday, 30, the year is 2026
30     The date is Saturday, 31, the year is 2026
Name: date, dtype: object

## Ejercicio 2
Para entender el rendimiento de cada tienda, calcula las ganancias por venta medias de los datos del ejercicio.

In [34]:
#run this cell to create the dataset
df_exp = pd.DataFrame({
    'Shop Name': ['Madrid', 'Barcelona', 'Sevilla'],
    'Monday': ["100€", "200€", "150€"],
    'Tuesday': ["90€", "80€", "70€"],
    'Wednesday': ["120€", "150€", "110€"],
    'Thursday': ["100€", "90€", "120€"],
    'Friday': ["70€", "110€", "130€"]
})

df_exp

   Shop Name Monday Tuesday Wednesday Thursday Friday
0     Madrid   100€     90€      120€     100€    70€
1  Barcelona   200€     80€      150€      90€   110€
2    Sevilla   150€     70€      110€     120€   130€

In [35]:
#TODO

  Monday Tuesday Wednesday Thursday Friday
0    100      90       120      100     70
1    200      80       150       90    110
2    150      70       110      120    130

   Shop Name Monday Tuesday Wednesday Thursday Friday
0     Madrid    100      90       120      100     70
1  Barcelona    200      80       150       90    110
2    Sevilla    150      70       110      120    130

  Monday Tuesday Wednesday Thursday Friday
0    100      90       120      100     70
1    200      80       150       90    110
2    150      70       110      120    130

Monday       object
Tuesday      object
Wednesday    object
Thursday     object
Friday       object
dtype: object

   Monday  Tuesday  Wednesday  Thursday  Friday
0     100       90        120       100      70
1     200       80        150        90     110
2     150       70        110       120     130

0     96.0
1    126.0
2    116.0
dtype: float64

   Shop Name  Monday  Tuesday  Wednesday  Thursday  Friday  weekly_avg_ax1
0     Madrid     100       90        120       100      70            96.0
1  Barcelona     200       80        150        90     110           126.0
2    Sevilla     150       70        110       120     130           116.0

# Ejercicio 3 
Feature Engineering con Regex, Str Ops, Numpy
- extrae las distancias y conviértelas a unidades con sentido

1.3.1. Crea una columna llamada distancias
- usa regex para extraer los números
- usa .astype() para convertirlos en el tipo adecuado

1.3.2. Crea una columna llamada unidades
- usa regex para extraer las unidades
- entiende los valores que aparecen en la columna unidad

1.3.3. Convierte las millas a kilómetros

In [46]:
#run this cell to create the dataset
df_distances = pd.DataFrame({
    "city1": ["Madrid", "Madrid", "Madrid", "London", "London", "London"],
    "city2": ["Barcelona", "Valencia", "Sevilla", "Manchester", "Liverpool", "Birmingham"],
    "distance": ["505 kilometres", "303KM", "390.5 km", "163 miles", "220 mi.", "miles: 120"]
})

In [47]:
#TODO

0      505
1       303
2    390.5
3      163
4      220
5       120
Name: distance, dtype: object

In [50]:
df_distances

    city1       city2        distance  raw_units
0  Madrid   Barcelona  505 kilometres      505.0
1  Madrid    Valencia           303KM      303.0
2  Madrid     Sevilla        390.5 km      390.5
3  London  Manchester       163 miles      163.0
4  London   Liverpool         220 mi.      220.0
5  London  Birmingham      miles: 120      120.0

In [52]:
df_distances

    city1       city2        distance  raw_units    in_Km
0  Madrid   Barcelona  505 kilometres      505.0  505.000
1  Madrid    Valencia           303KM      303.0  303.000
2  Madrid     Sevilla        390.5 km      390.5  390.500
3  London  Manchester       163 miles      163.0  262.267
4  London   Liverpool         220 mi.      220.0  353.980
5  London  Birmingham      miles: 120      120.0  193.080

# Ejercicio 4

Sin ejecutar este código, su resultado...

```python
import re

re.sub(r'e','a', 'hello my friends')
```
Elige la respuesta correcta:

    a. sustituye la 'e' por la 'a' en 'hello my friends'
    b. sustituye la 'a' for 'e' en 'hello my friends'
    c. sustituye la primera 'e' por la 'a'
    d. sustituye la primera 'a' por la 'e'

In [ ]:
# respuesta

# Ejercicio 5

¿Qué devolverá la siguiente expresión regular que usa **lookbehind negativo**? (¡Cuidado! Es negativo).
Razona tu respuesta **SIN EJECUTAR** el código.

```python
import re

sentence = "I like python.\nI do not like Python."

re.findall(r'(?<!I\sdo\snot\slike\s)\w+\.',sentence)
```


Select the correct answer:

    a. ['python.', 'ython.']
    b. ['python.]
    c. ['I like python.\n']
    d. ['I like python.']

In [ ]:
# respuesta